### ISSUE TITLE
A few options which i think could be useful

### ISSUE THREAD

**Issue by Magicmaan** [LotuxPunk/Handles#20] opened 2020-01-07 20:05 UTC
The tardis has a few functions that arent currently utilised that i think would be useful for example; as of now you can't rotate the exterior to face a direction, also once you've launched flight you can't end it so maybe activating the command again will stop it, stealth mode,stabiliser and HADS aren't able to be controlled.

**Comment by LotuxPunk** [comment] 2020-01-07 20:08
Thanks ! I'll wok on that at the end of January/ start of February and it'll be available on a final version for the 1.12.2. After that i'll work on the 1.14.4 version !

**Comment by LotuxPunk** [comment] 2020-01-07 20:08
Duplicate of #18

**Closed as completed by LotuxPunk** 2020-01-07 20:08 UTC
Labels: duplicate, enhancement
